services:
  - type: web
    name: royal-table-api
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /menu

    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_PATH
        value: /tmp/restaurant.db
      - key: RESTAURANT_CAPACITY
        value: 50
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
      - key: RESERVATION_EMAIL
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        value: https://nbehera46-source.github.io

