(()=>{
  try{localStorage.removeItem("royalTableTheme")}catch(_){}
  document.documentElement.removeAttribute("data-theme");
  document.documentElement.removeAttribute("data-theme-preference");
  document.addEventListener("DOMContentLoaded",()=>{
    if(document.body.dataset.adminUi==="true")setupAdmin();
  });
  function setupAdmin(){const nav=document.querySelector(".admin-nav"),title=document.getElementById("adminViewTitle"),subtitle=document.getElementById("adminViewSubtitle"),shell=document.querySelector(".admin-dashboard"),header=shell?.querySelector(":scope > header"),groups={overview:[".stats-grid",".analytics-grid",".analytics-layout",".analytics-panel",".operations-section"],reservations:[".top-bar",".stats-grid",".filters",".table-wrapper"],billing:[".top-bar",".filters",".table-wrapper"],menu:[".menu-section"],operations:[".operations-section"],analytics:[".analytics-grid",".analytics-layout",".analytics-panel"]},copy={overview:["Overview","Today’s essentials, alerts and recent performance at a glance."],reservations:["Reservations & Orders","Find a guest, open their booking, create orders and send KOTs."],billing:["Billing & Payments","Open a reservation to adjust itemized billing, record payment or print a receipt."],menu:["Menu","Manage dishes, availability, prices and imagery."],operations:["Operations","Team access, kitchen workload, inventory and grocery alerts."],analytics:["Analytics & AI","Revenue, service patterns and server-grounded operational intelligence."]};
    const drawerButton=document.createElement("button");drawerButton.type="button";drawerButton.className="admin-drawer-toggle";drawerButton.setAttribute("aria-label","Open navigation");drawerButton.setAttribute("aria-expanded","false");drawerButton.innerHTML='<span></span><span></span><span></span>';shell?.prepend(drawerButton);const closeDrawer=()=>{shell?.classList.remove("admin-drawer-open");drawerButton.setAttribute("aria-expanded","false")};drawerButton.addEventListener("click",()=>{const open=shell.classList.toggle("admin-drawer-open");drawerButton.setAttribute("aria-expanded",String(open))});document.addEventListener("keydown",e=>{if(e.key==="Escape")closeDrawer()});
    const modules=[...new Set(Object.values(groups).flatMap(s=>[...document.querySelectorAll(s)]))];const open=view=>{modules.forEach(el=>el.classList.add("admin-module-hidden"));(groups[view]||groups.overview).forEach(s=>document.querySelectorAll(s).forEach(el=>el.classList.remove("admin-module-hidden")));[title.textContent,subtitle.textContent]=copy[view]||copy.overview;nav.querySelectorAll("a[data-view]").forEach(a=>{const active=a.dataset.view===view;a.classList.toggle("active",active);if(active)a.setAttribute("aria-current","page");else a.removeAttribute("aria-current")});history.replaceState(null,"",`#${view}`);closeDrawer();scrollTo({top:0,behavior:"smooth"})};nav.addEventListener("click",e=>{const a=e.target.closest("a[data-view]");if(a){e.preventDefault();open(a.dataset.view)}else if(e.target.closest("a"))closeDrawer()});header?.addEventListener("click",e=>{if(e.target===header)closeDrawer()});open(location.hash.slice(1)||"overview");
  }
})();
