(()=>{
  const KEY="royalTableTheme";let timer;
  const solar=(date,lat,lng,rise)=>{const rad=Math.PI/180,day=Math.floor((Date.UTC(date.getFullYear(),date.getMonth(),date.getDate())-Date.UTC(date.getFullYear(),0,0))/86400000),hour=lng/15,t=day+((rise?6:18)-hour)/24,M=.9856*t-3.289,L=(M+1.916*Math.sin(rad*M)+.02*Math.sin(2*rad*M)+282.634)%360,RA=Math.atan(.91764*Math.tan(rad*L))/rad,quadrant=x=>Math.floor(x/90)*90;RA=(RA+quadrant(L)-quadrant(RA))/15;const sinDec=.39782*Math.sin(rad*L),cosDec=Math.cos(Math.asin(sinDec)),cosH=(Math.cos(rad*90.833)-sinDec*Math.sin(rad*lat))/(cosDec*Math.cos(rad*lat));if(cosH>1||cosH< -1)return null;const H=(rise?360-Math.acos(cosH)/rad:Math.acos(cosH)/rad)/15,T=H+RA-.06571*t-6.622,utc=(T-hour+24)%24;return new Date(Date.UTC(date.getFullYear(),date.getMonth(),date.getDate(),0,Math.round(utc*60)))};
  const fallback=()=>matchMedia("(prefers-color-scheme: dark)").matches?"dark":((new Date().getHours()<6||new Date().getHours()>=18)?"dark":"light");
  const auto=(coords)=>{let mode=fallback();if(coords){const now=new Date(),rise=solar(now,coords.latitude,coords.longitude,true),set=solar(now,coords.latitude,coords.longitude,false);if(rise&&set)mode=(now>=rise&&now<set)?"light":"dark"}return mode};
  const apply=(choice,coords)=>{document.documentElement.dataset.theme=choice==="auto"?auto(coords):choice;document.documentElement.dataset.themePreference=choice;document.querySelectorAll(".theme-switcher button").forEach(b=>b.setAttribute("aria-pressed",String(b.dataset.themeChoice===choice)));clearTimeout(timer);if(choice==="auto")timer=setTimeout(()=>apply("auto",coords),60000)};
  const choose=(choice)=>{localStorage.setItem(KEY,choice);if(choice==="auto"&&navigator.geolocation)navigator.geolocation.getCurrentPosition(p=>apply(choice,p.coords),()=>apply(choice),{maximumAge:86400000,timeout:5000});else apply(choice)};
  document.addEventListener("DOMContentLoaded",()=>{const control=document.createElement("div");control.className="theme-switcher";control.setAttribute("aria-label","Appearance");control.innerHTML='<button type="button" data-theme-choice="light">Light</button><button type="button" data-theme-choice="dark">Dark</button><button type="button" data-theme-choice="auto">Auto</button>';document.body.append(control);control.addEventListener("click",e=>{const c=e.target.dataset.themeChoice;if(c)choose(c)});choose(localStorage.getItem(KEY)||"auto");
    if(document.body.dataset.adminUi==="true")setupAdmin();
  });
  function setupAdmin(){const nav=document.querySelector(".admin-nav"),title=document.getElementById("adminViewTitle"),subtitle=document.getElementById("adminViewSubtitle"),groups={overview:[".stats-grid",".analytics-grid",".analytics-layout",".analytics-panel",".operations-section"],reservations:[".top-bar",".stats-grid",".filters",".table-wrapper"],billing:[".top-bar",".filters",".table-wrapper"],menu:[".menu-section"],operations:[".operations-section"],analytics:[".analytics-grid",".analytics-layout",".analytics-panel"]},copy={overview:["Overview","Today’s essentials, alerts and recent performance at a glance."],reservations:["Reservations & Orders","Find a guest, open their booking, create orders and send KOTs."],billing:["Billing & Payments","Open a reservation to adjust itemized billing, record payment or print a receipt."],menu:["Menu","Manage dishes, availability, prices and imagery."],operations:["Staff, Kitchen & Stock","Team access, kitchen workload, inventory and grocery alerts."],analytics:["Analytics & AI","Revenue, service patterns and server-grounded operational intelligence."]};
    const modules=[...new Set(Object.values(groups).flatMap(s=>[...document.querySelectorAll(s)]))];const open=view=>{modules.forEach(el=>el.classList.add("admin-module-hidden"));(groups[view]||groups.overview).forEach(s=>document.querySelectorAll(s).forEach(el=>el.classList.remove("admin-module-hidden")));[title.textContent,subtitle.textContent]=copy[view]||copy.overview;nav.querySelectorAll("a[data-view]").forEach(a=>a.classList.toggle("active",a.dataset.view===view));history.replaceState(null,"",`#${view}`);scrollTo({top:0,behavior:"smooth"})};nav.addEventListener("click",e=>{const a=e.target.closest("a[data-view]");if(a){e.preventDefault();open(a.dataset.view)}});open(location.hash.slice(1)||"overview");
  }
})();
